// <auto-generated />
using System;
using CyberAsset.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberAsset.API.Migrations
{
    [DbContext(typeof(CyberAssetDbContext))]
    [Migration("20260117190802_AjanSutunlari_Manual")]
    partial class AjanSutunlari_Manual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberAsset.API.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<string>("CpuInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiskCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OsName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OS_Name");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("OS_Version");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("RamCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecsCpu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Specs_CPU");

                    b.Property<int?>("SpecsRamGb")
                        .HasColumnType("int")
                        .HasColumnName("Specs_RAM_GB");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateOnly?>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__Assets__3214EC0783F18087");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex(new[] { "Ipaddress" }, "IX_Assets_IPAddress");

                    b.HasIndex(new[] { "Name" }, "IX_Assets_Name");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("CyberAsset.API.Models.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__AssetTyp__3214EC07F2A25AEE");

                    b.ToTable("AssetTypes");
                });

            modelBuilder.Entity("CyberAsset.API.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Departme__3214EC07A145D2F1");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CyberAsset.API.Models.DetectedVulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DetectedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FixedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<int>("VulnerabilityId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Detected__3214EC07B4F9EB5A");

                    b.HasIndex("AssetId");

                    b.HasIndex("VulnerabilityId");

                    b.HasIndex(new[] { "Status" }, "IX_DetectedVulns_Status");

                    b.ToTable("DetectedVulnerabilities");
                });

            modelBuilder.Entity("CyberAsset.API.Models.InstalledSoftware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Installe__3214EC07DA6B4CF7");

                    b.HasIndex("AssetId");

                    b.ToTable("InstalledSoftware", (string)null);
                });

            modelBuilder.Entity("CyberAsset.API.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Messages__3214EC07CF991F32");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CyberAsset.API.Models.PerformanceMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CpuUsagePercent")
                        .HasColumnType("int");

                    b.Property<int?>("DiskFreeSpaceGb")
                        .HasColumnType("int")
                        .HasColumnName("DiskFreeSpaceGB");

                    b.Property<int?>("RamUsagePercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Performa__3214EC074A37688A");

                    b.HasIndex("AssetId");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("CyberAsset.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("User");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC070687EF84");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4CFED9F03")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105342CBF0A2F")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users", t =>
                        {
                            t.HasTrigger("trg_UserRoleAudit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CyberAsset.API.Models.UserAuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NewRole")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldRole")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OperationType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__UserAudi__5E5486487EF1719F");

                    b.ToTable("UserAuditLogs");
                });

            modelBuilder.Entity("CyberAsset.API.Models.VulnerabilityDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CveCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CVE_Code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SeverityScore")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Vulnerab__3214EC07D4856570");

                    b.HasIndex(new[] { "CveCode" }, "UQ__Vulnerab__A5147B246776CBFC")
                        .IsUnique();

                    b.ToTable("VulnerabilityDefinitions");
                });

            modelBuilder.Entity("CyberAsset.API.Models.WebAccessLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AccessTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__WebAcces__3214EC076D4A81C0");

                    b.HasIndex("AssetId");

                    b.ToTable("WebAccessLogs");
                });

            modelBuilder.Entity("CyberAsset.API.Models.Asset", b =>
                {
                    b.HasOne("CyberAsset.API.Models.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Assets__AssetTyp__47DBAE45");

                    b.HasOne("CyberAsset.API.Models.User", "AssignedUser")
                        .WithMany("Assets")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Assets__Assigned__48CFD27E");

                    b.Navigation("AssetType");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("CyberAsset.API.Models.DetectedVulnerability", b =>
                {
                    b.HasOne("CyberAsset.API.Models.Asset", "Asset")
                        .WithMany("DetectedVulnerabilities")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DetectedV__Asset__534D60F1");

                    b.HasOne("CyberAsset.API.Models.VulnerabilityDefinition", "Vulnerability")
                        .WithMany("DetectedVulnerabilities")
                        .HasForeignKey("VulnerabilityId")
                        .IsRequired()
                        .HasConstraintName("FK__DetectedV__Vulne__5441852A");

                    b.Navigation("Asset");

                    b.Navigation("Vulnerability");
                });

            modelBuilder.Entity("CyberAsset.API.Models.InstalledSoftware", b =>
                {
                    b.HasOne("CyberAsset.API.Models.Asset", "Asset")
                        .WithMany("InstalledSoftwares")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Installed__Asset__4BAC3F29");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CyberAsset.API.Models.Message", b =>
                {
                    b.HasOne("CyberAsset.API.Models.User", "SenderUser")
                        .WithMany("Messages")
                        .HasForeignKey("SenderUserId")
                        .IsRequired()
                        .HasConstraintName("FK__Messages__Sender__6383C8BA");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("CyberAsset.API.Models.PerformanceMetric", b =>
                {
                    b.HasOne("CyberAsset.API.Models.Asset", "Asset")
                        .WithMany("PerformanceMetrics")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Performan__Asset__59FA5E80");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CyberAsset.API.Models.User", b =>
                {
                    b.HasOne("CyberAsset.API.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Users__Departmen__3F466844");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CyberAsset.API.Models.WebAccessLog", b =>
                {
                    b.HasOne("CyberAsset.API.Models.Asset", "Asset")
                        .WithMany("WebAccessLogs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__WebAccess__Asset__5EBF139D");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("CyberAsset.API.Models.Asset", b =>
                {
                    b.Navigation("DetectedVulnerabilities");

                    b.Navigation("InstalledSoftwares");

                    b.Navigation("PerformanceMetrics");

                    b.Navigation("WebAccessLogs");
                });

            modelBuilder.Entity("CyberAsset.API.Models.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("CyberAsset.API.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CyberAsset.API.Models.User", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CyberAsset.API.Models.VulnerabilityDefinition", b =>
                {
                    b.Navigation("DetectedVulnerabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
